# Spring Boot Application Properties
server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/jira_clone

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.jira=DEBUG
